
-- First, let's clear any existing data and insert fresh sample data
DELETE FROM grant_call_details;

-- Insert comprehensive sample grant data
INSERT INTO grant_call_details (
  title,
  organisation,
  description,
  subtitle,
  eligibility,
  application_closing_date,
  max_funding_per_project,
  min_funding_per_project,
  total_funding_per_call,
  currency,
  keywords,
  contact_name,
  contact_title,
  contact_email,
  contact_phone,
  eligible_cost_categories,
  evaluation_criteria,
  application_process,
  eligible_organisations,
  industry_sectors,
  original_url,
  cofinancing_required,
  cofinancing_level_min,
  cofinancing_level_max,
  program,
  grant_type
) VALUES 
(
  'Innovation Grant for SMEs',
  'Vinnova',
  'This grant supports small and medium enterprises in developing innovative solutions for sustainable technology.',
  'Supporting innovation in Swedish SMEs',
  'Small and medium enterprises registered in Sweden with less than 250 employees',
  '2024-12-31',
  5000000,
  500000,
  50000000,
  'SEK',
  '["innovation", "SME", "technology", "sustainability"]'::jsonb,
  'Anna Andersson',
  'Program Manager',
  'anna.andersson@vinnova.se',
  '+46 8 123 456 78',
  '["personnel costs", "equipment", "materials", "travel"]'::jsonb,
  'Innovation potential, market impact, technical feasibility, team competence',
  'Online application through Vinnova portal, two-stage evaluation process',
  '["small enterprises", "medium enterprises", "research institutes"]'::jsonb,
  '["technology", "manufacturing", "healthcare", "environment"]'::jsonb,
  'https://www.vinnova.se/example-grant-1',
  true,
  20.0,
  50.0,
  'Innovation Program',
  'Innovation Grant'
),
(
  'Green Technology Development Fund',
  'Formas',
  'Funding for research and development of green technologies and sustainable solutions.',
  'Advancing green technology innovation',
  'Research institutions, universities, and companies with R&D capabilities',
  '2024-11-30',
  10000000,
  1000000,
  100000000,
  'SEK',
  '["green technology", "sustainability", "R&D", "environment"]'::jsonb,
  'Erik Eriksson',
  'Research Coordinator',
  'erik.eriksson@formas.se',
  '+46 8 775 40 00',
  '["research costs", "equipment", "personnel", "travel"]'::jsonb,
  'Scientific quality, environmental impact, innovation potential',
  'Two-stage application process with peer review',
  '["universities", "research institutes", "companies"]'::jsonb,
  '["environmental technology", "energy", "transportation"]'::jsonb,
  'https://www.formas.se/example-grant-2',
  false,
  null,
  null,
  'Green Technology Program',
  'Research Grant'
),
(
  'Digital Transformation Support',
  'Tillväxtverket',
  'Support for SMEs to implement digital transformation initiatives.',
  'Accelerating digital adoption in Swedish businesses',
  'Small and medium enterprises with digital transformation needs',
  '2024-10-15',
  2000000,
  200000,
  25000000,
  'SEK',
  '["digital transformation", "SME", "technology adoption", "automation"]'::jsonb,
  'Maria Svensson',
  'Digital Advisor',
  'maria.svensson@tillvaxtverket.se',
  '+46 8 681 91 00',
  '["software licenses", "consulting", "training", "equipment"]'::jsonb,
  'Digital maturity, business impact, implementation plan',
  'Online application with digital readiness assessment',
  '["small enterprises", "medium enterprises"]'::jsonb,
  '["manufacturing", "retail", "services", "technology"]'::jsonb,
  'https://www.tillvaxtverket.se/example-grant-3',
  true,
  30.0,
  null,
  'Digital Transformation Program',
  'Digitalization Grant'
);
