
-- Insert some sample grant data for testing
INSERT INTO grant_call_details (
  title,
  organisation,
  description,
  subtitle,
  eligibility,
  application_closing_date,
  max_grant_per_project,
  min_grant_per_project,
  total_funding_amount,
  currency,
  keywords,
  contact_name,
  contact_title,
  contact_email,
  contact_phone,
  eligible_cost_categories,
  evaluation_criteria,
  application_process,
  eligible_organisations,
  industry_sectors,
  original_url
) VALUES 
(
  'Innovation Grant for SMEs',
  'Vinnova',
  'This grant supports small and medium enterprises in developing innovative solutions for sustainable technology.',
  'Supporting innovation in Swedish SMEs',
  'Small and medium enterprises registered in Sweden with less than 250 employees',
  '2024-12-31',
  5000000,
  500000,
  50000000,
  'SEK',
  '["innovation", "SME", "technology", "sustainability"]'::jsonb,
  'Anna Andersson',
  'Program Manager',
  'anna.andersson@vinnova.se',
  '+46 8 123 456 78',
  '["personnel costs", "equipment", "materials", "travel"]'::jsonb,
  'Innovation potential, market impact, technical feasibility, team competence',
  'Online application through Vinnova portal, two-stage evaluation process',
  '["small enterprises", "medium enterprises", "research institutes"]'::jsonb,
  '["technology", "manufacturing", "healthcare", "environment"]'::jsonb,
  'https://www.vinnova.se/example-grant-1'
),
(
  'Green Technology Development Fund',
  'Energimyndigheten',
  'Funding for development of renewable energy and energy efficiency technologies.',
  'Advancing green technology solutions',
  'Companies and research organizations working on renewable energy projects',
  '2024-11-15',
  10000000,
  1000000,
  100000000,
  'SEK',
  '["renewable energy", "green technology", "energy efficiency"]'::jsonb,
  'Erik Eriksson',
  'Senior Advisor',
  'erik.eriksson@energimyndigheten.se',
  '+46 16 544 200',
  '["R&D costs", "demonstration projects", "equipment"]'::jsonb,
  'Environmental impact, commercial potential, technical innovation',
  'Application deadline November 15th, decision in February',
  '["companies", "research organizations", "universities"]'::jsonb,
  '["energy", "environment", "technology"]'::jsonb,
  'https://www.energimyndigheten.se/example-grant-2'
),
(
  'Digital Transformation Initiative',
  'Tillväxtverket',
  'Support for companies implementing digital solutions to improve competitiveness.',
  'Digitizing Swedish businesses',
  'Swedish companies looking to implement digital transformation projects',
  '2024-10-30',
  2000000,
  200000,
  25000000,
  'SEK',
  '["digitalization", "digital transformation", "competitiveness"]'::jsonb,
  'Maria Svensson',
  'Business Development Manager',
  'maria.svensson@tillvaxtverket.se',
  '+46 8 681 91 00',
  '["software", "training", "consulting", "hardware"]'::jsonb,
  'Digital maturity, business impact, implementation plan',
  'Rolling applications, quarterly decisions',
  '["SMEs", "large enterprises", "startups"]'::jsonb,
  '["retail", "manufacturing", "services", "logistics"]'::jsonb,
  'https://www.tillvaxtverket.se/example-grant-3'
);
