// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsxzjjleatrbgbuqrcel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeHpqamxlYXRyYmdidXFyY2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NTQ1OTksImV4cCI6MjA2NDUzMDU5OX0.er9QQNWB2rlGNH8ApbffPcS14mk39VFyQJ7Ed5ycrG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);